---
title: "pathwayanalysis"
author: "Josh Gilheany (22221584)"
date: "2023-06-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library('biomaRt')
library(tibble)

get_upregulated <- function(df){

	key <- intersect(rownames(df)[which(df$log2FoldChange>=0)], 
	                 rownames(df)[which(df$padj<=0.05)])

    results <- as.data.frame((df)[which(rownames(df) %in% key),])
	return(results)
}

get_downregulated <- function(df){

  	key <- intersect(rownames(df)[which(df$log2FoldChange<0)], 
  	                 rownames(df)[which(df$padj<=0.05)])

  	results <- as.data.frame((df)[which(rownames(df) %in% key),])
  	return(results)
}




get_regulated <- function(df){

  	key <- intersect(rownames(df),
  	       rownames(df)[which(df$padj<=0.05)])

  	results <- as.data.frame((df)[which(rownames(df) %in% key),])
  	return(results)
}
```


```{r}
setwd("/media/josh/EXTERNAL_USB/Project/MSc_2023_data/FQuants")

ftable <- read.table("Results.txt")

ftable

setwd("/media/josh/EXTERNAL_USB/Project/MSc_2023_data/MQuants")

mtable <- read.table("Results.txt")

mtable


#reads in table with all mouse ENSEMBL ids, MGI and HGNC for later addition
setwd("/media/josh/EXTERNAL_USB/Project/MSc_2023_data")

convert <- read.csv2("Convert_ENSEMBL_MGI_HGNC.txt", sep="")

convert
```

```{r}
setwd("/media/josh/EXTERNAL_USB/Project/MSc_2023_data/MQuants")
#nrow(mtable)
#nrow(get_upregulated(mtable))
#nrow(get_downregulated(mtable))


upregmale <- get_upregulated(mtable)
downregmale <- get_downregulated(mtable)
regmale <- get_regulated(mtable)

write.table(upregmale, "UDEGMale.txt")
write.table(downregmale, "DDEGMale.txt")
write.table(regmale, "DEGMale.txt")

regmale <- regmale %>% 
  rownames_to_column(var = "Genes")
upregmale <- upregmale %>% 
  rownames_to_column(var = "Genes")
downregmale <- downregmale %>% 
  rownames_to_column(var = "Genes")


diffgenesmale <- pull(regmale, "Genes")
print(diffgenesmale, quote=FALSE)
updiffgenesmale <- pull(upregmale, "Genes")
downdiffgenesmale <- pull(downregmale, "Genes")


write.table(diffgenesmale, "diffgenesmale.txt", quote=FALSE, row.names = FALSE, col.names = FALSE)
write.table(updiffgenesmale, "updiffgenesmale.txt", quote=FALSE, row.names = FALSE, col.names = FALSE)
write.table(downdiffgenesmale, "downdiffgenesmale.txt", quote=FALSE, row.names = FALSE, col.names = FALSE)

setwd("/media/josh/EXTERNAL_USB/Project/MSc_2023_data/FQuants")

nrow(ftable)
nrow(get_upregulated(ftable))
nrow(get_downregulated(ftable))

upregfemale <- get_upregulated(ftable)
downregfemale <- get_downregulated(ftable)
regfemale <- get_regulated(ftable)

write.table(upregfem, "UDEGFemale.txt")
write.table(downregfem, "DDEGFemale.txt")
write.table(regfem, "DEGFemale.txt")

regfemale <- regfemale %>% 
  rownames_to_column(var = "Genes")
upregfemale <- upregfemale %>% 
  rownames_to_column(var = "Genes")
downregfemale <- downregfemale %>% 
  rownames_to_column(var = "Genes")


diffgenesfemale <- pull(regfemale, "Genes")
print(diffgenesmale, quote=FALSE)
updiffgenesfemale <- pull(upregfemale, "Genes")
downdiffgenesfemale <- pull(downregfemale, "Genes")


write.table(diffgenesfemale, "diffgenesfemale.txt", quote=FALSE, row.names = FALSE, col.names = FALSE)
write.table(updiffgenesfemale, "updiffgenesfemale.txt", quote=FALSE, row.names = FALSE, col.names = FALSE)
write.table(downdiffgenesfemale, "downdiffgenesfemale.txt", quote=FALSE, row.names = FALSE, col.names = FALSE)



#upregmale[,0]

```

```{r}
listEnsembl()
ensembl <- useEnsembl(biomart = "genes")
datasets <- listDatasets(ensembl)
head(datasets)
searchDatasets(mart = ensembl, pattern = "mmusculus")
```

```{r}
ensembl <- useDataset(dataset = "mmusculus_gene_ensembl", mart = ensembl)
```



```{r}

#for (x in rownames(upregfem)) {print(x)}

upregfem[,-4]
mart <- useDataset("mmusculus_gene_ensembl", useMart("ensembl"))
genes <- rownames(upregfem)
upregfem$id <- NA
G_list <- getBM(filters= "ensembl_gene_id", attributes= c("external_gene_name"),values=genes,mart= mart)

G_list
listAttributes(ensembl)

datasets <- listDatasets(ensembl)
head(datasets)
searchDatasets(mart = ensembl, pattern = "mmusculus")
```

```{r}
human = useMart("ensembl", dataset = "hsapiens_gene_ensembl")
mouse = useMart("ensembl", dataset = "mmusculus_gene_ensembl")
```



```{r}
library(biomaRt)


convertMouseGeneList <- function(x){

require("biomaRt")


human = useMart("ensembl", dataset = "hsapiens_gene_ensembl", host="https://dec2021.archive.ensembl.org")

mouse = useMart("ensembl", dataset = "mmusculus_gene_ensembl", host="https://dec2021.archive.ensembl.org")

genesV2 = getLDS(attributes = c("ensembl_gene_id"), filters = "ensembl_gene_id", values = x , mart = mouse, 
                 attributesL = c("hgnc_id"), martL = human, uniqueRows=T, host="https://dec2021.archive.ensembl.org")

humanx <- unique(genesV2[, 2])


# Print the first 6 genes found to the screen

print(head(humanx))

return(humanx)

}
```

```{r}
hgncdiffmale <- convertMouseGeneList(diffgenesmale)

hgncdiffemale <- convertMouseGeneList(diffgenesfemale)

?getLDS

```
```{r}
setwd("/media/josh/EXTERNAL_USB/Project/MSc_2023_data")

convert <- read.csv2("Convert_ENSEMBL_MGI_HGNC.txt", sep="")



```


